# имя нужно обязательно - с помощью него производится регистрация в общем сервисе
spring:
  application:
    name: issue-service
server:
  port: 8680
#  данные об Eureka для регистрации
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka